export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CHECK_AUTH_REQUEST = "CHECK_OUT_REQUEST";
export const CHECK_AUTH_SUCCESS = "CHECK_OUT_SUCCESS";
export const CHECK_AUTH_ERROR = "CHECK_OUT_ERROR";
