export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_DATA_ERROR";

export const FETCH_DATA_DETAIL_REQUEST = "FETCH_DATA_DETAIL_REQUEST";
export const FETCH_DATA_DETAIL_SUCCESS = "FETCH_DATA_DETAIL_SUCCESS";
export const FETCH_DATA_DETAIL_ERROR = "FETCH_DATA_DETAIL_ERROR";

export const CHANGE_DATA_REQUEST = "CHANGE_DATA_REQUEST";
export const CHANGE_DATA_SUCCESS = "CHANGE_DATA_SUCCESS";
export const CHANGE_DATA_ERROR = "CHANGE_DATA_ERROR";
